set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Enable line numbers
set number
" Enable syntax highlighting
syntax on

colorscheme solarflare 

" Show the filename in the window titlebar
set title

" Highlight searches
set hlsearch
" Ignore case of searches
set ignorecase

" set clipboard=unnamedplus,unnamed,autoselect
set clipboard+=unnamedplus

set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set pastetoggle=<F10>

imap jj <Esc>

" vnoremap // y:%s/<C-R>///g<CR>
nnoremap // :%s/<C-R>///g<CR>

set scrolloff=8

" From Vimbits
" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

set ruler " Char location info
" Command-line tab completion
set wildmenu
set title " to set terminal window name to file name
" set cursorline
"
set nobomb
set backspace=indent,eol,start
" set mouse=a
set mouse=niv
" set dropdown to match solarized light
highlight Pmenu ctermfg=254 ctermbg=241
highlight PmenuSel ctermfg=254 ctermbg=136 cterm=bold
highlight Search cterm=NONE ctermfg=white ctermbg=red
highlight MatchParen cterm=bold ctermbg=none ctermfg=magenta
set incsearch
"This unsets the 'last search pattern' register by hitting return
nnoremap <silent><CR> :nohlsearch<CR><CR>

set undofile   " Maintain undo history between sessions
set undodir=~/.vim/undodir

set showcmd " Show me what I'm typing
set noerrorbells " No beeps

set nocursorcolumn " speed up syntax highlighting
set nocursorline

set nocursorcolumn " speed up syntax highlighting
set nocursorline

set statusline+=%F

set history=200

" set tags=tags;/
nmap ,f :FufFileWithCurrentBufferDir<CR>
nmap ,b :FufBuffer<CR>
nmap ,t :FufTaggedFile<CR>
